// scripts/gen-skill.ts
//
// C3 / KEH-169 - Regenerate the "Verb reference" section of SKILL.md from the
// verb registry. The section is fenced by marker comments; this script
// replaces everything between them with a fresh `generateVerbReference(VERBS)`.
//
//   bun run gen:skill           rewrite SKILL.md in place
//   bun run check:skill         exit non-zero if SKILL.md is stale
//
// The generator imports the same `VERBS` array that `arcops verbs --json`
// serializes (src/commands/verbs.ts -> printJson({ verbs: VERBS })), so the
// doc and the capability-discovery endpoint can never drift. A drift test
// (src/verbs/skill-drift.test.ts) enforces this under `bun test`.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { VERBS } from '../src/verbs/registry';
import { generateVerbReference } from '../src/verbs/to-markdown';

const SKILL_PATH = resolve(import.meta.dir, '..', 'SKILL.md');
const BEGIN = '<!-- BEGIN VERB REFERENCE - generated by `bun run gen:skill`; do not edit by hand -->';
const END = '<!-- END VERB REFERENCE -->';

function renderSkill(current: string): string {
  const body = generateVerbReference(VERBS);
  const beginIdx = current.indexOf(BEGIN);
  const endIdx = current.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Could not locate verb-reference markers in ${SKILL_PATH}.\n` +
      `Expected to find:\n  ${BEGIN}\n  ...verb tables...\n  ${END}\n` +
      `Add the markers to SKILL.md (or restore them) and re-run.`,
    );
  }
  const before = current.slice(0, beginIdx + BEGIN.length);
  const after = current.slice(endIdx);
  return `${before}\n\n${body}\n\n${after}`;
}

const check = process.argv.includes('--check');
const current = readFileSync(SKILL_PATH, 'utf8');
const next = renderSkill(current);

if (next === current) {
  console.log('SKILL.md verb reference is up to date.');
  process.exit(0);
}
if (check) {
  console.error('SKILL.md verb reference is stale. Run `bun run gen:skill` to regenerate.');
  process.exit(1);
}
writeFileSync(SKILL_PATH, next);
console.log(`Regenerated verb reference in ${SKILL_PATH}.`);
