// src/verbs/skill-drift.test.ts
//
// C3 / KEH-169 - SKILL.md drift gate. Asserts the "Verb reference" section
// committed in SKILL.md matches a fresh generation from the registry. If a
// verb is added or changed without running `bun run gen:skill`, this test
// fails - so the doc can never silently drift from the registry (design §6.2
// Phase 4). Runs under the existing `bun test` CI gate; no extra CI job.

import { test, expect } from 'bun:test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { VERBS } from './registry';
import { generateVerbReference } from './to-markdown';

const SKILL_PATH = resolve(import.meta.dir, '..', '..', 'SKILL.md');
const BEGIN = '<!-- BEGIN VERB REFERENCE - generated by `bun run gen:skill`; do not edit by hand -->';
const END = '<!-- END VERB REFERENCE -->';

test('SKILL.md verb reference is in sync with the registry', () => {
  const skill = readFileSync(SKILL_PATH, 'utf8');
  const begin = skill.indexOf(BEGIN);
  const end = skill.indexOf(END);
  expect(begin, 'BEGIN marker present in SKILL.md').toBeGreaterThan(-1);
  expect(end, 'END marker present in SKILL.md').toBeGreaterThan(-1);
  expect(end, 'END marker after BEGIN marker').toBeGreaterThan(begin);

  const committed = skill.slice(begin + BEGIN.length, end).trim();
  const fresh = generateVerbReference(VERBS).trim();
  expect(committed, 'SKILL.md is stale - run `bun run gen:skill` to regenerate').toBe(fresh);
});
